### ISSUE TITLE
Doesn't work with form-data 2.3.2+

### ISSUE THREAD

**Issue by Sammael1106** [twolfson/css-validator#10]
Hi there! Thank you for your plugin.

Unfortunately, one of my dependecies set `form-data` to 2.3.2 version. And after it css-validator has an error: 
```
Uncaught TypeError: form.getHeaders is not a function at ValidationStream.generateTextRequest (validation-stream.js:74)
```

**Comment by twolfson** [comment]
I'm quite busy for the next couple days. Would you be interested in submitting a PR for this?

**Comment by twolfson** [comment]
This has been resolved by @antongolub in #18 and released in `0.10.0`
