### PR TITLE
Up deps, fix vuls, update fixtures

### LINKED ISSUE #10: Doesn't work with form-data 2.3.2+
Hi there! Thank you for your plugin.

Unfortunately, one of my dependecies set `form-data` to 2.3.2 version. And after it css-validator has an error: 
```
Uncaught TypeError: form.getHeaders is not a function at ValidationStream.generateTextRequest (validation-stream.js:74)
```

### PR DESCRIPTION
**Pull request by antongolub**
* up deps / fix known vuls
* use CLI `opt.delay` instead of `sleep`
* update fixtures. Replace rawgit.com with gitcdn.link

closes #10

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1 +1,2 @@
 node_modules/
+yarn.lock
```
Comment (twolfson) [inline .gitignore:2]: We don't use Yarn in this repo so shouldn't really need this =/ This seems like it should be in the developer's global `.gitignore` -- or they should use `npm install`

Will leave it though I guess, doesn't really hurt anyone, though might confuse them

File: lib/cli.js [hunk 2]
```diff
@@ -29,8 +29,8 @@ exports._parse = function (argv, _console, callback) {
       DEFAULT_SLEEP_MS)
     .option('--concurrency <concurrency>',
       'Amount of requests to run in parallel, defaults to ' + DEFAULT_CONCURRENCY, DEFAULT_CONCURRENCY)
-    .option('--usermedium <usermedium>', 'Medium where the CSS will be used (e.g. `all` (service default), `print`, `screen`)')
-    .option('--profile <profile>', 'CSS profile to use for validation (e.g. `css3svg` (service default), `css21`, `svg`)')
+    .option('--usermedium <usermedium>', 'Medium where the CSS will be used (e.g. `all` (service default), `print`, `screen`)') // jscs:disable
```
Comment (twolfson) [inline lib/cli.js:32]: I'm guessing this is for line length, would prefer we silence that rule explicitly. Will update

File: lib/cli.js [hunk 3]
```diff
@@ -96,7 +99,7 @@ exports._parse = function (argv, _console, callback) {
         }
 
         // Continue
-        setTimeout(cb, program.sleep);
+        setTimeout(cb, opts.delay);
```
Comment (twolfson) [inline lib/cli.js:102]: :+1: Nice catch, surprised nobody reported this earlier o_o

File: lib/cli.js [hunk 4]
```diff
@@ -54,17 +57,17 @@ exports._parse = function (argv, _console, callback) {
     }
 
     // Otherwise, perform our validation
-    async.eachOfLimit(filepathContentArr, program.concurrency,
+    async.eachOfLimit(filepathContentArr, opts.concurrency,
```
Comment (twolfson) [inline lib/cli.js:60]: Was confused why we needed this change -- turns out in Commander@7 they moved it to an inner object to avoid unsafe usage:

https://github.com/tj/commander.js/pull/1409

https://github.com/tj/commander.js/blob/4aaaa9de3fd09401afe3894483193ba0e2e512d7/CHANGELOG.md#700-2021-01-15

**Review by twolfson — APPROVED** [review]
LGTM, thanks for all the work here =)

**Comment by twolfson** [comment]
This has been landed in `0.10.0`. Thanks again for the PR =)
